### ISSUE TITLE
初赛代码跑出的结果不对劲

### ISSUE THREAD

**Issue by disillusion028** [Morde-kaiser/HuaWei-CodeCraft2017#1]
刚刚拿这份初赛的代码跑800节点case0的时候跑了个19w的，结果收敛特别快，是不是代码后来修改了ga没用上啊？

**Comment by luckzhiwei** [comment]
同问，我git clone了您的代码之后，本地跑一个800的case0，有39w，想知道代码是不是有注释没有打开

**Comment by xfguo-ucas** [comment]
不好意思，初赛代码deploy.cpp里面调用的粒子群作为启发式，应该把optimize(graph)注释掉，然后打开遗传。代码已经更新啦 @disillusion028 @luckzhiwei

**Comment by disillusion028** [comment]
赞，多谢分享～

**Comment by luckzhiwei** [comment]
赞，谢谢分享
